import { createClient } from "@/lib/supabase/server"
import { type NextRequest, NextResponse } from "next/server"

export async function GET(req: NextRequest) {
  try {
    const supabase = await createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { searchParams } = new URL(req.url)
    const contentId = searchParams.get("id")
    const format = searchParams.get("format") || "json"

    if (!contentId) {
      return NextResponse.json({ error: "Content ID is required" }, { status: 400 })
    }

    // Get the content from database
    const { data: content, error } = await supabase
      .from("generated_content")
      .select("*")
      .eq("id", contentId)
      .eq("user_id", user.id)
      .single()

    if (error || !content) {
      return NextResponse.json({ error: "Content not found" }, { status: 404 })
    }

    let downloadContent = ""
    let filename = ""
    let contentType = "text/plain"

    if (format === "json") {
      downloadContent = JSON.stringify(content, null, 2)
      filename = `red-rose-ai-content-${contentId}.json`
      contentType = "application/json"
    } else if (content.content_type === "text") {
      downloadContent = `# Generated by Red Rose AI - 100% FREE
# Content ID: ${contentId}
# Generated: ${content.created_at}
# Prompt: ${content.prompt}

${content.result_data?.text || "No text content available"}

---
Generated completely FREE by Red Rose AI
More powerful than paid alternatives - zero cost forever!`
      filename = `red-rose-ai-text-${contentId}.txt`
    } else if (content.content_type === "code") {
      const extension =
        content.result_data?.language === "python" ? "py" : content.result_data?.language === "html" ? "html" : "js"
      downloadContent = `// Generated by Red Rose AI - 100% FREE
// Content ID: ${contentId}
// Generated: ${content.created_at}
// Prompt: ${content.prompt}
// Language: ${content.result_data?.language}
// Framework: ${content.result_data?.framework}

${content.result_data?.code || "No code content available"}

/*
Generated completely FREE by Red Rose AI
More powerful than paid alternatives - zero cost forever!
*/`
      filename = `red-rose-ai-code-${contentId}.${extension}`
    } else if (content.content_type === "image") {
      // For images, return the metadata and description
      downloadContent = `# Red Rose AI - FREE Image Generation
# Content ID: ${contentId}
# Generated: ${content.created_at}
# Prompt: ${content.prompt}

${content.result_data?.description || "No description available"}

Image URL: ${content.result_url}

---
Generated completely FREE by Red Rose AI
More powerful than paid alternatives - zero cost forever!`
      filename = `red-rose-ai-image-${contentId}.txt`
    }

    // Return file as download
    return new NextResponse(downloadContent, {
      headers: {
        "Content-Type": contentType,
        "Content-Disposition": `attachment; filename="${filename}"`,
        "X-Generated-By": "Red Rose AI - 100% FREE",
      },
    })
  } catch (error) {
    console.error("Download content error:", error)
    return NextResponse.json({ error: "Failed to download content" }, { status: 500 })
  }
}
